name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Services
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          cd Lab\ Work\ №5/code/client && npm install
          cd ../gateway && npm install
          cd ../post-service && npm install
          cd ../user-service && npm install

      - name: Build Services
        run: |
          cd Lab\ Work\ №5/code/client && CI=false npm run build
          cd ../gateway && npm run build
          cd ../post-service && npm run build
          cd ../user-service && npm run build

  deploy:
    name: Deploy to DockerHub
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build and Push Docker Images
        run: |
          docker build -t client-1:latest ./Lab\ Work\ №5/code/client
          docker tag client-1:latest ilyatyulin/client-1:latest
          docker build -t gateway-1:latest ./Lab\ Work\ №5/code/gateway
          docker tag gateway-1:latest ilyatyulin/gateway-1:latest
          docker build -t post-service-1:latest ./Lab\ Work\ №5/code/post-service
          docker tag post-service-1:latest ilyatyulin/post-service-1:latest
          docker build -t user-service-1:latest ./Lab\ Work\ №5/code/user-service
          docker tag user-service-1:latest ilyatyulin/user-service-1:latest

          docker push ilyatyulin/client-1:latest
          docker push ilyatyulin/gateway-1:latest
          docker push ilyatyulin/post-service-1:latest
          docker push ilyatyulin/user-service-1:latest
