name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Сборка проекта начата
        run: |
          echo "Build is running..."
      - name: Смена директории
        run: |
          cd "client"
      - name: Сборка клиента
        run: |
          echo "client building..."
      - name: Смена директории
        run: |
          cd ../gateway
      - name: Сборка маршрутизатора
        run: |
          echo "gateway building..."
      - name: Смена директории
        run: |
          cd ../post-service
      - name: Сборка сервиса постов
        run: |
          echo "post-service building..."
      - name: Смена директории
        run: |
          cd ../user-service
      - name: Сборка сервиса пользователей
        run: |
          echo "user-service successfully!"
      - name: Сборка проекта закончена
        run: |
          echo "Build completed successfully!"

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Деплой проекта начат
        run: |
          echo "Deployment is running..."
      - name: Создание папки
        run: |
          mkdir -p blog-app
      - name: Копирование docker-compose
        run: |
          cp docker-compose.yml blog-app/
      - name: Смена директории
        run: |
          cd blog-app
      - name: Остановка запущенных контейнеров
        run: |
          docker-compose down
      - name: Сборка образов
        run: |
          docker-compose up -d
      - name: Деплой проекта закончен
        run: |
          echo "Deployment completed successfully!"
