name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Сборка проекта начата
        run: echo "Build is running..."

      - name: Сборка клиента
        run: echo "client building..."

      - name: Сборка маршрутизатора
        run: echo "gateway building..."

      - name: Сборка сервиса постов
        run: echo "post-service building..."

      - name: Сборка сервиса пользователей
        run: echo "user-service successfully!"

      - name: Сборка проекта закончена
        run: echo "Build completed successfully!"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Деплой проекта начат
        run: echo "Deployment is running..."

      - name: Создание папки
        run: mkdir -p blog-app

      - name: Деплой проекта закончен
        run: echo "Deployment completed successfully!"
